#!/bin/bash
# RetroLX poor man's makedb
# lightweight pacman database creation
# @rtissera
#
# 20210629 - Initial revision

HOST_DIR="$1"

# Generate pacman repository database
PATH="${HOST_DIR}/usr/bin:${PATH}" repo-add "retrolx.db.tar.gz" *.pkg.tar.zst

# Workaround for local packages on FAT (no symlinks)
rm retrolx.db
rm retrolx.files
cp retrolx.db.tar.gz retrolx.db
cp retrolx.files.tar.gz retrolx.files

# Cleanup old files
#[ -f retrolx.db.tar.gz.old ] && rm retrolx.db.tar.gz.old
#[ -f retrolx.files.tar.gz.old ] && rm retrolx.files.tar.gz.old
