# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Feature request
description: Suggest a new feature or improve an existing one
title: "[Feature Request]: "
labels: ["Enhancement / Feature Request"]
# assignees:
#   - lilo-san
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: |
        A concise description of the feature you want

        Include step by step examples of how the feature should work under various circumstances
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: |
        Give a reason why you want this feature
        - How will it make things easier for you?
        - How does this feature help your enjoyment of the emulator?
        - What does it provide that isn't being provided currently?

        We are not accepting feature requests related to the libretro core as it's being maintained separately at this time
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: |
        Provide examples of the feature as implemented by other software

        Include screenshots or video if you like to help demonstrate how you'd like this feature to work
    validations:
      required: true
