#!/bin/bash

BOOTCONF="/boot/retrolx-boot.conf"

# only at start
test "$1" != "start" && exit 0

# true if triggers are not available or not set to do so
if ! grep -qE '^[ ]*install[ ]*=[ ]*true[ ]*$' "${BOOTCONF}"
then
    exit 0
fi

# only when install is wanted
if grep -qE '^[ ]*install[ ]*=[ ]*true[ ]*$' "${BOOTCONF}"
then
    sync
    /usr/share/retrolx/scripts/install-packages.sh
    sync
    /usr/share/retrolx/scripts/install-content.sh
    sync

    # Remove the trigger
    mount -o remount,rw /boot && sed -i -e s+'^[ ]*install'+'#install'+ "${BOOTCONF}" && mount -o remount,ro /boot
fi

#Cleanup, restore screen, reboot
clear > /dev/tty1
shutdown -r now
sleep 120
exit 0
