#!/bin/sh
#
# KSMBD network share script

securityenabled="$(/usr/bin/batocera-settings-get system.security.enabled)"

if [ "$securityenabled" = "1" ]; then
    CONFIGFILE="/etc/samba/smb-secure.conf"
else
    CONFIGFILE="/etc/samba/smb.conf"
fi

# Make directories.
mkdir -p /var/lock/subsys

RETVAL=0

start() {
	enabled="$(/usr/bin/batocera-settings-get system.samba.enabled)"
	if [ "$enabled" = "0" ]; then
	  echo "SMB services: disabled"
	  exit 0
        fi

	echo -n "Starting SMB services: "
	modprobe ksmbd
	RETVAL1=$?
	ksmbd.adduser -a retrolx -p retrolx
	RETVAL2=$?
	ksmbd.addshare -a retrolx -o "guest ok = yes, writable = yes, path = /userdata"
	RETVAL3=$?
	ksmbd.mountd
	RETVAL4=$?
	echo "done"

	[ $RETVAL1 -eq 0 -a $RETVAL2 -eq 0 -a $RETVAL3 -eq 0 -a $RETVAL4 -eq 0 ] && touch /var/lock/subsys/smb || \
	   RETVAL=1
	return $RETVAL
}

stop() {
	echo -n "Shutting down SMB services: "
	ksmbd.addshare -d retrolx
	RETVAL1=$?
	ksmbd.adduser -d retrolx
	RETVAL2=$?
	ksmbd.control -s
	RETVAL3=$?
	rmmod ksmbd
	RETVAL4=$?
	echo "done"

	[ $RETVAL1 -eq 0 -a $RETVAL2 -eq 0 -a $RETVAL3 -eq 0 -a $RETVAL4 -eq 0 ] && rm -f /var/lock/subsys/smb
	echo "done"
	return $RETVAL
}

restart() {
	stop
	start
}

reload() {
        echo -n "Reloading smb.conf file: "
	ksmbd.control -s
	ksmbd.mountd
	RETVAL=$?
	echo "done"
	return $RETVAL
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
