default:
  options:
    video_threaded: true
    retroarch.video_rotation: 0 # for people upgrading
    # menu retroarch
    retroarch.menu_driver: rgui
    retroarch.menu_widget_scale_auto: "false"
    retroarch.menu_widget_scale_factor: 1.5

n64:
  options:
    mupen64plus.Video-General.Rotate: 0 # for people upgrading
psp:
  options:
    frameskip: automatic
    ppsspp.General.InternalScreenRotation: 0 # for people upgrading
nds:
  emulator: libretro
  core:     melonds
